/* eslint-disable no-unused-vars */
const app = jest.fn();
const db = jest.fn();
const auth = jest.fn();
const login = jest.fn();
const regist = jest.fn();
const currentUserInfo = jest.fn();
const savePost = jest.fn();
const getPosts = jest.fn();
const onGetPost = jest.fn();
const deletePost = jest.fn();
const getPost = jest.fn();
const updatePost = jest.fn();
const loginGoogle = jest.fn();
const provider = jest.fn();
const logOut = jest.fn();
